import { sayHello } from '@hyunwlee/lib'
import { A11yHidden, Button, Container, Input, Label, ProgressBar } from '@hyunwlee/ui'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useMediaQuery } from '@hyunwlee/hook'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const targetReached = useMediaQuery(600);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {sayHello()}
        <A11yHidden as='h1'>monorepo test(you can see me?)</A11yHidden>
        <Container>{"I'm Container from ui"}</Container>
        <Button>{"I'm Button from ui"}</Button>
        <Label htmlFor='hi'>{"I'm Label from ui"}</Label>
        <Input id='hi' type="text" value="I'm Input from ui (read only)" readOnly style={{textAlign: 'center'}}></Input>
        <ProgressBar className={styles.progressBar} completed={42} isVisibleAmount/>
        {`current viewport <= 600px: ${targetReached}`}
      </main>
    </>
  )
}
