import { A11yHidden, Button, Container, Input, Label, ProgressBar } from '@hyunwlee/ui'
import * as React from 'react';
import { Inter } from 'next/font/google'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useMediaQuery, useModal } from '@hyunwlee/hook'
import { ReactNode } from 'react'
import ReactDOM from 'react-dom';

const inter = Inter({ subsets: ['latin'] })

const Modal = ({isShown, hide, modalContent, headerText}: {
  isShown: boolean,
  hide: () => void,
  modalContent: ReactNode,
  headerText: string,
  }) => {
  const modal = (<>
    <div className={`${styles.backDrop}`} onClick={hide}/>
    <div
      aria-modal
      aria-labelledby={headerText}
      tabIndex={-1}
      role='dialog'
    >
      <div className={`${styles.wrapper}`}>
        {modalContent}
      </div>
    </div>
  </>);
  return isShown ? ReactDOM.createPortal(modal, document.body) : null;
}

export default function Home() {
  const targetReached = useMediaQuery(600);
  const {isShown, toggle} = useModal();
  return(
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <A11yHidden as='h1'>monorepo test(you can see me?)</A11yHidden>
        <Container>{"I'm Container from ui"}</Container>
        <Button>{"I'm Button from ui"}</Button>
        <Label htmlFor='hi'>{"I'm Label from ui"}</Label>
        <Input id='hi' type="text" value="I'm Input from ui (read only)" readOnly style={{textAlign: 'center'}}></Input>
        <ProgressBar className={styles.progressBar} completed={42} isVisibleAmount/>
        {`current viewport <= 600px: ${targetReached}`}
        <Button onClick={toggle}>모달 버튼</Button>
      </main>
      <Modal 
          isShown={isShown}
          hide={toggle}
          modalContent={
            <div tabIndex={0}>
              <div className={`${styles.panel}`}>hello world!</div>
              <Button onClick={toggle}>X</Button>
            </div>
          } 
          headerText={'ship'}
      />
    </React.Fragment>
  )
}

